### ISSUE TITLE
A better interface for getting innerHTML than _content

### ISSUE THREAD

**Issue by kof** [PixelsCommander/ReactiveElements#23]
_content is really a hack, we need a better approach.

**Comment by aindlq** [comment]
What do you think about approach in https://github.com/greenish/react-mount? What I like there is that it is possible to expose any react component as custom element, e.g. https://github.com/react-bootstrap/react-bootstrap/issues/506 . Actually maybe it would make sense to join forces with react-mount :)

**Comment by PixelsCommander** [comment]
You can use document.registerReact() ouside of component`s file in the same
way mount do. If I understnad you correctly and that is the thing that
makes it strong.

2015-07-25 22:52 GMT+02:00 Artem Kozlov <notifications@github.com>:

**Comment by PixelsCommander** [comment]
@aindlq Got it. You mean renaming props._children to props.children which makes it React compatible out of the box. @kof What do you think on this one? Should we do that?

**Comment by aindlq** [comment]
@PixelsCommander not really. My understanding is that it is not possible to use props._children directly in the render method because it is DocumentFragment, but react expects ReactElemenet or unsafe html there. react-mount compiles custom tag content using jsx compiler, as result children property is real react object. Advantage of this approach is that it is possible to use almost any existing react component as custom element without any changes to the source code.

**Comment by PixelsCommander** [comment]
JSX compiler... Sounds reasonable.

**Comment by kof** [comment]
@PixelsCommander .children is already used in my PR

**Comment by kof** [comment]
https://github.com/PixelsCommander/ReactiveElements/pull/43/files#diff-7321489e1afd632bdbdd2a6a1629cf6dR60

2 props, children and container ... both are absolutely required

**Comment by PixelsCommander** [comment]
Got it. Give me a day to dive into you big pull request in details.

**Comment by kof** [comment]
children as a react elements seems to be a good idea

**Comment by kristianmandrup** [comment]
What is the status on this? :)

**Comment by kof** [comment]
my PR has been merged, the next step is to make children react elements instead of dom elements to be fully compatible with react.

**Comment by PixelsCommander** [comment]
But JSX transformer is deprecated. Are there other ways around to implement
that?

2015-09-29 13:17 GMT+02:00 Oleg Slobodskoi <notifications@github.com>:

**Comment by kof** [comment]
Why do you need a JSX transformer to create react elements?

**Comment by PixelsCommander** [comment]
How would you transform JSX otherwise?

Or you want to convert HTML elements to React elements by traversing the
whole tree? I can barely understand why would this make sense. To place
{this.children} in render function? But it looks like a pretty a lot of job
on traversal and convertion every time we create an element.

2015-09-29 13:28 GMT+02:00 Oleg Slobodskoi <notifications@github.com>:

**Comment by kof** [comment]
1. We could use "createNodesFromMarkup" and then create react elements. But yes it means traversing the tree of custom element children.
1. I also don't see lots of use cases for using custom element with predefined inner elements together with react. I see it as an edge case where it should not be a lot of elements inside.
1. Well if user wants to misuse this possibility and creates an overhead through this, its not libs fault. The approach how user creates custom element is not specific to this project, also user has full control about children.

**Comment by jackfranklin** [comment]
Closing this because it's very old, but please let me know if you would like this reopened :)
