### ISSUE TITLE
"Handling attributes change" section of README requires another example or may be removal

### ISSUE THREAD

**Issue by FractalizeR** [PixelsCommander/ReactiveElements#32]
Since 0.13 version of ReactJS (http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html) props are immutable. So, I think that example needs to be rewritten so as not to promote bad practices. 

I am not also sure with this change changing attributes of a component is a good idea (since attributes are imported into a component as props, which are immutable). There should be other ways used to communicate to React component via Flux-like technics or something like that. May be, it will be better to mark this section as "not recommended to be used".

**Comment by PixelsCommander** [comment]
Attributes are actually React.props by syntax. So I do not expect many
changes there. setAttribute is not used that intensively to create
performance issues immutability is implemented to get rid of. Recent change
is more about avoiding problems caused by intensive variables mutations.
And as for attributes - not that many people will mutate them many times
per second as some do with variables. So I do not like idea to restrict
users to use HTMLElement.setAttribute which is a good HTML practice since
ancient ages.

There is another possibility to operate component - call it`s method as
HTMLElement.componentMethod(someParam); and it is reflected in demo. I will
promote it into README.

2015-02-25 9:31 GMT+01:00 Vladislav Rastrusny <notifications@github.com>:

**Comment by FractalizeR** [comment]
Well, I do not think there is a need to restrict anything. It is just that 
>  future versions of React will incorporate performance optimizations assuming that props aren't mutated

So, that example in readme where props were mutated by using attributes may even stop working. I think users must be notified.

**Comment by PixelsCommander** [comment]
Agree

2015-02-25 11:10 GMT+01:00 Vladislav Rastrusny <notifications@github.com>:

**Comment by FractalizeR** [comment]
Ok ;)
