### ISSUE TITLE
Issue with _content property

### ISSUE THREAD

**Issue by anakinjay** [PixelsCommander/ReactiveElements#36]
Not sure if this is a documentation issue, a code issue, or something I'm doing wrong.

According to the documentation, you should be able to access your custom element's content using:
{ this.props._content }

However, _content appears to be returning the whole element object rather than it's contents, so to get the content, you have to use:
{ this.props._content.innerHTML }

So either:
A.) Documentation needs updated to state _content returns an object
B.) _content needs to return the innerHTML directly
C.) I'm doing something really really wrong.  haha.

**Comment by PixelsCommander** [comment]
It is not correct. _content is an abstract DocumentFragment containing all node children since it is impossible to store many of them in single property. Of course innerHTML is available on it as well. Also you may use myNode.appendChild(node._content) and it will append only childs without a wrapper and this is how documentFragment works...
